version: "3"

services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=admin
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:
